# Generated by Django 2.1.2 on 2018-10-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181022_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField(null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Collection')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
